version: "2"
run:
  go: "1.26"
  tests: false
linters:
  enable:
    - exhaustruct
    - exhaustive
    - errorlint
    - gocritic
    - godot
    - govet
    - noctx
    - predeclared
    - reassign
    - staticcheck
    - unused
  settings:
    exhaustruct:
      include:
        - 'github\.com/sillen102/simba/.*'
      exclude:
        - '.*/openapi31\..*'
        - '.*/http\.Server'
        - '.*/configloader\..*'
    govet:
      enable:
        - printf
        - shadow
