version: "2"
run:
  go: "1.26"
  tests: false
linters:
  enable:
    - bodyclose
    - exhaustive
    - exhaustruct
    - errcheck
    - errorlint
    - gocritic
    - godot
    - govet
    - noctx
    - predeclared
    - reassign
    - staticcheck
    - unused
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    exhaustruct:
      include:
        - 'github.com/sillen102/simba/telemetry/.*'
    govet:
      enable:
        - printf
        - shadow
