version: "2"
run:
  go: "1.26"
  tests: false
linters:
  enable:
    - exhaustruct
    - exhaustive
    - errorlint
    - gocritic
    - godot
    - govet
    - noctx
    - predeclared
    - reassign
    - staticcheck
    - unused
linters-settings:
  exhaustruct:
    include:
      - 'github.com/sillen102/simba/websocket/.*'
  govet:
    enable:
      - printf
      - shadow
