[tasks.test]
description = "Run tests"
run = "gotestsum --format=short-verbose"

[tasks.test-race]
description = "Run tests with race detector"
run = "gotestsum --format=short-verbose -- -v -race ./..."

[tasks.lint]
description = "Run linters"
run = [
    "golangci-lint run --timeout 5m",
    "nilaway -test=false ./..."
]

[tasks.verify]
description = "Run all verification tasks such as test and lint"
run = { tasks = ["test", "lint"] }

[tasks.tidy]
description = "Run go mod tidy"
run = "go mod tidy -v"

[tasks.update-deps]
description = "Update dependencies"
run = "go get -u ./..."
